// Marketplace links for each variant.
export const marketplaceLinks: Record<string, Record<string, string>> = {
  'pkt-a': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmxkMC6KGV-g0IsE/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Zbi',
    blibli: 'https://blibli.onelink.me/GNtk/j8iyfwby',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240772',
  },
  'pkt-b': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmxPyTUpGJ-tgdgD/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Zbx',
    blibli: 'https://blibli.onelink.me/GNtk/6o4dq6gm',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240768',
  },
  'pkt-c': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmxpEBFScV-bwQ0o/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Z1o',
    blibli: 'https://blibli.onelink.me/GNtk/m71wq1t8',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240756',
  },
  'pkt-d': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmxW8ABGt5-zKKXc/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Zcg',
    blibli: 'https://blibli.onelink.me/GNtk/yaqsn1qf',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240763',
  },
  'pkt-e': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmxvRoBFcX-U05mM/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Zcw',
    blibli: 'https://blibli.onelink.me/GNtk/gvtl03en',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240759',
  },
  'pkt-f': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmxT7YjLYh-5ybzJ/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Z3t',
    blibli: 'https://blibli.onelink.me/GNtk/92nt6u7o',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240758',
  },
  'pkt-g': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQ1BK5mQT-x0wgT/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Zec',
    blibli: 'https://blibli.onelink.me/GNtk/xxs5styg',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240767',
  },
  'pkt-h': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQeBrxbSN-I96Tl/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7ZVP',
    blibli: 'https://blibli.onelink.me/GNtk/crmzscup',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240770',
  },
  'pkt-i': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQLkLyDej-mO7Vz/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Z4a',
    blibli: 'https://blibli.onelink.me/GNtk/mikriv5t',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240762',
  },
  'pkt-j': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQ6xeAJke-2HD00/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Z4N',
    blibli: 'https://blibli.onelink.me/GNtk/vf6kh4x8',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240754',
  },
  'pkt-k': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQh33uFJW-nJ5aR/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Z4B',
    blibli: 'https://blibli.onelink.me/GNtk/b2bu4xuk',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240764',
  },
  'pkt-l': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQSHFHXyN-p0Qpr/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7ZU0',
    blibli: 'https://blibli.onelink.me/GNtk/t9qtbog2',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240769',
  },
  'pkt-m': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQfoF3bQB-phBiV/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7Zok',
    blibli: 'https://blibli.onelink.me/GNtk/x26gmqwp',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240766',
  },
  'pkt-n': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQfp1WWyR-ZJvAQ/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7ZsS',
    blibli: 'https://blibli.onelink.me/GNtk/wjw5960r',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240760',
  },
  'pkt-o': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQurkDQCT-Tx6eG/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl8up2',
    blibli: 'https://blibli.onelink.me/GNtk/fyxajxy8',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240775',
  },
  'pkt-p': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQQBBFXD5-pwGO8/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl70Js',
    blibli: 'https://blibli.onelink.me/GNtk/5hdyi4fb',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240771',
  },
  'pkt-q': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQbdHg7WC-txGUs/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7bVc',
    blibli: 'https://blibli.onelink.me/GNtk/ihndv7r4',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240773',
  },
  'pkt-r': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQG2NWswv-SqAqb/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7bjy',
    blibli: 'https://blibli.onelink.me/GNtk/11qj2ay6',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240757',
  },
  'pkt-s': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQtQX52xR-6DcCE/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl8FfJ',
    blibli: 'https://blibli.onelink.me/GNtk/7l5ffqbg',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240755',
  },
  'pkt-t': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQcS7Cjew-D6n4N/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7bwe',
    blibli: 'https://blibli.onelink.me/GNtk/rthx6v90',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240774',
  },
  'pkt-u': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQTfpQPTT-e2W0q/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7YaH',
    blibli: 'https://blibli.onelink.me/GNtk/qkepvti4',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240761',
  },
  'pkt-v': {
    tiktok: 'https://vt.tokopedia.com/t/ZS9FmQKB9ybNM-6995m/',
    shopee: 'https://id.shp.ee/KNo42fc5',
    tokopedia: 'https://tk.tokopedia.com/ZS93nndBD/',
    lazada: 'https://s.lazada.co.id/s.Zl7YTz',
    blibli: 'https://blibli.onelink.me/GNtk/jn6nohi3',
    akulaku: 'https://ec-mall.akulaku.com/mobile/product/detail?spuId=544240765',
  },
};
